"""empty message

Revision ID: 8261cde18399
Revises: 1ab82c455a43
Create Date: 2024-05-02 15:34:16.672097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8261cde18399'
down_revision = '1ab82c455a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        

   # with op.batch_alter_table('comments', schema=None) as batch_op:
   #     batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('twitter')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('github')
        batch_op.drop_column('created_at')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('description')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
